### PR TITLE
build shared libraries (and nngcat executable) instead of static library

### PR DESCRIPTION
**Pull request by brendanf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Tested on my linux box, let's see if it works on the others...

This PR will break any package currently relying on the presence of the static library.  I'm not sure if any such package exists.  The guidance in [CFEP-18](https://github.com/conda-forge/cfep/blob/main/cfep-18.md) is that, if the static library is really required, it should be in a separate package called `nng-static`.

### CODE REVIEW

**Comment by brendanf** [comment]
As far as I can tell this is ready to go, unless there is concern about breaking other packages by no longer including the static library.  Another option would be to build both shared and static libraries; AFAIK the easiest way to do this would be through two different Cmake builds in different directories.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by carlodri** [comment]
Maybe we should add a test for the nngcat executable.

**Comment by brendanf** [comment]
@carlodri I implemented the test, everything looks good.

**Comment by carlodri** [comment]
thanks @brendanf!

**Pull request merged**
